openapi: 3.0.0
info:
  title: IBM Cloud Docs Helper
  version: 0.1.0
  description: |
   This skill uses generative AI to query IBM Cloud Docs stored as PDFs to provide prompt answers to user inquiries. 
   By automatically scanning and understanding PDF content, it accelerates information retrieval. 
   This approach streamlines user experience by delivering accurate responses from extensive documentation. 
  x-ibm-annotations: 'true'
  x-ibm-application-name: IBM Cloud Docs Helper
  x-ibm-application-id: ibmcloud-docs-query
  x-ibm-skill-type: imported
  x-ibm-application-icon: >-
    <svg width="800px" height="800px" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><circle cx="512" cy="512" r="512" style="fill:#0f62fe"/><path d="M223.9 611.5h112v16h-112v-16zm0-30.8h112v16.1h-112v-16.1zm31.9-30.7h48.1v16.1h-48.1V550zm0-30.7h48.1v16.1h-48.1v-16.1zm0-30.7h48.1v16.1h-48.1v-16.1zm0-30.8h48.1v16.1h-48.1v-16.1zm-31.9-30.7h112v16.1h-112v-16.1zm0-30.7h112v16.1h-112v-16.1zm128 200.4h172.3c2.9-4.9 5.1-10.4 6.4-16.1H351.9v16.1zm158.9-77.5H384v16.1h140.3c-3.6-6.1-8.1-11.5-13.5-16.1zm-126.9-30.7v16.1h126.9c5.3-4.5 9.8-9.9 13.4-16.1H383.9zm140.3-61.5H351.9v16.1h178.7c-1.4-5.6-3.6-11-6.4-16.1zm-52.9-30.7H351.9v16.1h160.5c-11.2-10.3-25.9-16.1-41.1-16.1zm-87.4 61.4h48v16.1h-48v-16.1zm96.1 16.1h50.2c1.4-5.1 2.2-10.6 2.2-16.1H480v16.1zM383.9 550h48v16.1h-48V550zm96.1 0v16.1h52.4c0-5.5-.7-11-2.2-16.1H480zm-128.1 77.4 119.3.2c16 0 30.4-6.2 41.2-16.1H351.9v15.9zM544 611.5h80v16h-80v-16zm0-30.8h80v16.1h-80v-16.1zm32-30.7h48v16.1h-48V550zm0-30.7h48v16.1h-48v-16.1zm70.3-92.2H544v16.1h107.8l-5.5-16.1zm-10.6-30.7H544v16.1h97.2l-5.5-16.1zM720 611.5h80.1v16H720v-16zm0-30.8h80.1v16.1H720v-16.1zm0-30.7h48v16.1h-48V550zm0-30.7h48v16.1h-48v-16.1zm0-14.6h48v-16.1h-91.5l-4.5 13-4.5-13H576v16.1h48v-14.8l5.1 14.8h85.8l5.1-14.8v14.8zm48.1-46.9h-80.9l-5.5 16.1h86.4v-16.1zm-59.6-61.4-5.5 16.1h97.2v-16.1h-91.7zm-36.5 231 5.5-15.9h-11.1l5.6 15.9zm-10.6-30.6h21.2l5.7-16.1h-32.6l5.7 16.1zm-10.8-30.7h42.8L699 550h-54l5.6 16.1zm-10.7-30.7h64.3l5.5-16.1h-75.3l5.5 16.1zM576 473.9h86.5l-5.5-16.1h-81v16.1zm116.3-30.7h107.8v-16.1H697.8l-5.5 16.1zm0 0" style="fill:#fff"/></svg>
servers:
  - url: https://yettobeadded.com
paths:
  /health:
    get:
      summary: Health Check
      description: Verify the health of API.
      operationId: health_check_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: string
                    example: pong
        '500':
          description: Internal server Error
  /answer:
    get:
      summary: IBM Cloud Docs
      description: Get answers from IBM Cloud Docs.
      operationId: conversation_answer_get
      parameters:
        - name: query
          in: query
          description: IBM Cloud docs based question.
          required: true
          schema:
            type: string
            title: Query IBM Cloud Docs
            x-ibm-show: true
            x-ibm-prompt : "What is your query?"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                properties:
                  IBM Cloud Docs Response:
                    type: string
                    x-ibm-show: true
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /image:
    get:
      summary: Get Image
      operationId: get_image_image_get
      parameters:
        - required: false
          schema:
            title: Url
            default: https://www.google.com/url?sa=i&url=https%3A%2F%2Fleaders.com%2Farticles%2Fbusiness%2Fibm-history%2F&psig=AOvVaw26M4kCxbNnDz1yXqqYNL87&ust=1691923577142000&source=images&cd=vfe&opi=89978449&ved=0CA4QjRxqFwoTCPiO6dL41oADFQAAAAAdAAAAABAI
          name: url
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
                properties:
                  Image shown:
                    type: string
                    x-ibm-show: true
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /support:
    get:
      summary: Quick Error Support
      description: Resolution for commonly seen errors
      operationId: common_error_support_support_get
      parameters:
        - required: true
          schema:
            type: string
            title: Support for error resolution
            x-ibm-show: true
            x-ibm-prompt : "Please mention the error faced?"
          name: query
          in: query
          description: Answers to frequent errors.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Support'
                properties:
                  Resolution suggested:
                    type: string
                    x-ibm-show: true
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /checklist:
    get:
      summary: New Hire Checklist
      operationId: new_hire_checklist_checklist_get
      description: Get the information required for new employees.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewHires'
                properties:
                  Presenting the first hand information for new hires:
                    type: string
                    x-ibm-show: true
components:
  securitySchemes:  # Add this section for security schemes
    api_key:
      type: apiKey
      name: X-API-Key
      in: header
  schemas:
    Support:
      type: object
      properties:
        Quick Error Resolution:
          type: object
          properties:
            description:
              type: string
            solution:
              type: string
    Image:
      type: object
      properties:
        Test Images:
          type: object
          properties:
            filename:
              type: string
            base64_encoded_data:
              type: string
              format: base64
    Hires:
      type: object
      properties:
        Team_Name:
          type: string
          enum:
            - GoldenEye
            - Support
            - Dreadnought
        Org:
          type: string
        About:
          type: string
        Technical_doc:
          type: string
        Coding_Guidelines:
          type: string
        Access_Requests:
          type: string
        Tech_Stack:
          type: string
        Start:
          type: string
    NewHires:
      type: object
      properties:
        IBM New Hires Support:
          type: array
          items:
            $ref: '#/components/schemas/Hires'
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
